/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nurseconsole1cserver.ServersSettings;

import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ServersSettingsForm extends javax.swing.JFrame {
    ServersTableModel serversTableModel;
    /**
     * Creates new form ServersSettings
     */
    public ServersSettingsForm() {        
        initComponents();
        ServersSettingsStorage serversSettings = new ServersSettingsStorage();
        Vector serversTableData = serversSettings.getCentralServers();
        serversTableModel = new ServersTableModel(serversTableData);
        serversList.setModel(serversTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        serversList = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        serverVersionLabel = new javax.swing.JLabel();
        serverAddressLabel = new javax.swing.JLabel();
        serverPortLabel = new javax.swing.JLabel();
        serverTestConnect = new javax.swing.JButton();
        serverPort = new javax.swing.JTextField();
        serverAddress = new javax.swing.JTextField();
        serverVersion = new javax.swing.JComboBox();
        serverAdd = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serversList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Версия", "Компьютер", "Порт"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        serversList.setName("serversList"); // NOI18N
        serversList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(serversList);
        serversList.getAccessibleContext().setAccessibleName("Servers");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Настройки сервера"));

        serverVersionLabel.setText("Версия сервера:");

        serverAddressLabel.setText("Компьютер:");

        serverPortLabel.setText("Порт:");

        serverTestConnect.setText("Проверить подключение");
        serverTestConnect.setMaximumSize(new java.awt.Dimension(162, 23));
        serverTestConnect.setMinimumSize(new java.awt.Dimension(162, 23));
        serverTestConnect.setName("serverTestConnect"); // NOI18N

        serverPort.setName("serverPort"); // NOI18N

        serverAddress.setName("serverAddress"); // NOI18N

        serverVersion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V8.1", "V8.2", "V8.3" }));
        serverVersion.setName("serverVersion"); // NOI18N

        serverAdd.setText("Добавить сервер");
        serverAdd.setName("serverAdd"); // NOI18N
        serverAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serverVersionLabel)
                            .addComponent(serverPortLabel)
                            .addComponent(serverAddressLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serverPort)
                            .addComponent(serverAddress)
                            .addComponent(serverVersion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(serverAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serverTestConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverVersionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverAddressLabel)
                    .addComponent(serverAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverPortLabel)
                    .addComponent(serverPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverTestConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverAdd)))
        );

        serverPort.getAccessibleContext().setAccessibleName("serverPort");
        serverAddress.getAccessibleContext().setAccessibleName("serverAddress");
        serverVersion.getAccessibleContext().setAccessibleName("serverVersion");

        Exit.setText("Закрыть");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Save.setText("Сохранить");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Delete.setText("Удалить");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(Save)
                    .addComponent(Delete)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverAddActionPerformed
        if (isAllFielsFilled()){
            String serverVersionValue = (String)(serverVersion.getSelectedItem());
            String serverAddressValue = serverAddress.getText();
            String serverPortValue = serverPort.getText();
            Object[] rowServer = {serverVersionValue, serverAddressValue, serverPortValue};
            serversTableModel.addRowTable(rowServer);
            serversList.setModel(serversTableModel);
            serversList.updateUI();
        }
    }//GEN-LAST:event_serverAddActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Vector serversTableData = serversTableModel.getTableData();
        ServersSettingsStorage serversSettings = new ServersSettingsStorage();
        serversSettings.setCentralServers(serversTableData);
    }//GEN-LAST:event_SaveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        int selectedRow = serversList.getSelectedRow();
        serversTableModel.delleteRowTable(selectedRow);
        serversList.setModel(serversTableModel);
        serversList.updateUI();
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServersSettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServersSettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServersSettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServersSettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ServersSettingsForm().setVisible(true);
            }
        });
    }
    
    private boolean isAllFielsFilled() {
        
        boolean allFielsFilled = true;
        String serverAddressValue = serverAddress.getText();
        if(serverAddressValue.isEmpty()){
            allFielsFilled = false;
            JOptionPane.showMessageDialog(null, "Не заполнен адрес компьютера сервера 1С:Предприятия.");
        }
        String serverPortValue = serverPort.getText();
        if(serverPortValue.isEmpty()){
            allFielsFilled = false;
            JOptionPane.showMessageDialog(null, "Не заполнен порт компьютера сервера 1С:Предприятия.");
        }
        
        return allFielsFilled;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Save;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton serverAdd;
    private javax.swing.JTextField serverAddress;
    private javax.swing.JLabel serverAddressLabel;
    private javax.swing.JTextField serverPort;
    private javax.swing.JLabel serverPortLabel;
    private javax.swing.JButton serverTestConnect;
    private javax.swing.JComboBox serverVersion;
    private javax.swing.JLabel serverVersionLabel;
    private javax.swing.JTable serversList;
    // End of variables declaration//GEN-END:variables
}